// source: robot.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.robot.Robot');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.robot.Helper');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.robot.Robot = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.robot.Robot.repeatedFields_, null);
};
goog.inherits(proto.robot.Robot, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.robot.Robot.displayName = 'proto.robot.Robot';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.robot.Robot.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.robot.Robot.prototype.toObject = function(opt_includeInstance) {
  return proto.robot.Robot.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.robot.Robot} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.robot.Robot.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    powersList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    speedLevel: jspb.Message.getFieldWithDefault(msg, 10, 0),
    helper: (f = msg.getHelper()) && proto.robot.Helper.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.robot.Robot}
 */
proto.robot.Robot.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.robot.Robot;
  return proto.robot.Robot.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.robot.Robot} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.robot.Robot}
 */
proto.robot.Robot.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addPowers(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSpeedLevel(value);
      break;
    case 11:
      var value = new proto.robot.Helper;
      reader.readMessage(value,proto.robot.Helper.deserializeBinaryFromReader);
      msg.setHelper(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.robot.Robot.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.robot.Robot.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.robot.Robot} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.robot.Robot.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPowersList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getSpeedLevel();
  if (f !== 0) {
    writer.writeInt32(
      10,
      f
    );
  }
  f = message.getHelper();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      proto.robot.Helper.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.robot.Robot.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.robot.Robot} returns this
 */
proto.robot.Robot.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.robot.Robot.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.robot.Robot} returns this
 */
proto.robot.Robot.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated string powers = 3;
 * @return {!Array<string>}
 */
proto.robot.Robot.prototype.getPowersList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.robot.Robot} returns this
 */
proto.robot.Robot.prototype.setPowersList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.robot.Robot} returns this
 */
proto.robot.Robot.prototype.addPowers = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.robot.Robot} returns this
 */
proto.robot.Robot.prototype.clearPowersList = function() {
  return this.setPowersList([]);
};


/**
 * optional int32 speed_level = 10;
 * @return {number}
 */
proto.robot.Robot.prototype.getSpeedLevel = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.robot.Robot} returns this
 */
proto.robot.Robot.prototype.setSpeedLevel = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional Helper helper = 11;
 * @return {?proto.robot.Helper}
 */
proto.robot.Robot.prototype.getHelper = function() {
  return /** @type{?proto.robot.Helper} */ (
    jspb.Message.getWrapperField(this, proto.robot.Helper, 11));
};


/**
 * @param {?proto.robot.Helper|undefined} value
 * @return {!proto.robot.Robot} returns this
*/
proto.robot.Robot.prototype.setHelper = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.robot.Robot} returns this
 */
proto.robot.Robot.prototype.clearHelper = function() {
  return this.setHelper(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.robot.Robot.prototype.hasHelper = function() {
  return jspb.Message.getField(this, 11) != null;
};


